### ISSUE TITLE
How to customize the navigation panel

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring#33]
Could you please specify the steps to customize/modify the components in the navigation panel of the UI, such as logo text, tooltips, etc. Thanks

**Comment by egorovpavel** [comment]
Hi @usmanazizgroupdocs, at this moment you are limited to toolbar buttons configuration in  `configuration.yaml`, however, we are investigating the possibility to either adding more configuration options or providing other means for customization.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel , Thanks for sharing the details. I have tried modifying some static resources (such as tooltips and the logo text "VIEWER") in the file _\src\main\resources\static\angular\viewer\src\app\viewer-app.component.html_ but the changes are not applied to the application when it is loaded in the browser. Is it the right way to modify static resources?

**Comment by egorovpavel** [comment]
Hi @usmanazizgroupdocs, just answered to a similar question  [here](https://github.com/groupdocs-total/GroupDocs.Total-for-Java-Spring/issues/67#issuecomment-507717514). Let me know if it works for you.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel, I have tried your provided [workflow ](https://github.com/groupdocs-total/GroupDocs.Total-for-Java-Spring/issues/67#issuecomment-507717514) and it worked. Regards
