### ISSUE TITLE
Integration with the JSP based application

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring#36]
This issue is raised via forum topic: [https://forum.groupdocs.com/t/regarding-groupdocs-java-document-viewer/7422/10](https://forum.groupdocs.com/t/regarding-groupdocs-java-document-viewer/7422/10)

> Our UI is designed in JSP so can we easily integrate your code in our project, and if we want to use your UI which you mentioned GroupDocs.Viewer for Java - Spring so can you please provide any support on how to integrate it in our project.

**Comment by koleslena** [comment]
Hi @usmanazizgroupdocs,
To use new viewer ui on your jsp page you need to specify js scripts and root angular tag, for example, in our sample
https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/blob/548164f2273b1ce3bb4ce12acbcefb7d31bb0ff6/src/main/resources/templates/viewer.html#L11
