### ISSUE TITLE
Error when running the latest release

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring#37]
I have faced the following error when running the latest application using the command: `mvn clean spring-boot:run`

> [error] Error: Could not find module "@angular-devkit/build-angular" from "D:\\GroupDocs.Viewer-for-Java-Spring\\client".
>     at Object.resolve (C:\Users\USMAN-PC\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\core\node\resolve.js:151:11)
>     at WorkspaceNodeModulesArchitectHost.resolveBuilder (C:\Users\USMAN-PC\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:31:40)
>     at BuildCommand.initialize (C:\Users\USMAN-PC\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:135:55)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

> `[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (build client) on project viewer-spring: Failed to run task: 'npm run --prefix client build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]`

After executing the command: `npm install --save-dev @angular-devkit/build-angular`, I got the following error message:

> [error] Error: Cannot find module '@angular/compiler-cli'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (C:\Users\USMAN-PC\Downloads\GroupDocs.Viewer-for-Java-Spring-master (4)\GroupDocs.Viewer-for-Java-Spring-master\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:12:24)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (C:\Users\USMAN-PC\Downloads\GroupDocs.Viewer-for-Java-Spring-master (4)\GroupDocs.Viewer-for-Java-Spring-master\node_modules\@ngtools\webpack\src\index.js:13:10)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by koleslena** [comment]
Hi @usmanazizgroupdocs ,
We have reproduced the problem on Windows, and we are investigating it now.

**Comment by usmanazizgroupdocs** [comment]
This issue is also raised in the forum topic: [https://forum.groupdocs.com/t/regarding-groupdocs-java-document-viewer/7422/13](https://forum.groupdocs.com/t/regarding-groupdocs-java-document-viewer/7422/13)

**Comment by egorovpavel** [comment]
@usmanazizgroupdocs this issue has been solved.
