### ISSUE TITLE
The Excel spreadsheet is not displayed properly

### ISSUE THREAD

**Issue by usmanazizgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring#43]
This issue was raised via the forum topic: [https://forum.groupdocs.com/t/the-spreadsheet-viewing-issue/7677](https://forum.groupdocs.com/t/the-spreadsheet-viewing-issue/7677).

> The spreadsheet is viewed properly as it is shown in excelsheet in windows.
> The spreadsheets sheets are displayed far different than actual we view in windows.
> Whether in the new version 1.19 it has been fixed.
> The excelsheet cells style is not followed also.

We also tried rendering the attached spreadsheet ([doc_viewer_list.xlsx](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/files/3749656/doc_viewer_list.xlsx)) and got the following result:
![SpreadsheetRendering](https://user-images.githubusercontent.com/16013722/67187439-a1508a00-f403-11e9-836c-abfb83115212.png)

**Comment by egorovpavel** [comment]
Hi @usmanazizgroupdocs, we added this issue to our roadmap and expect to release  UI for displaying cells documents until the end of this month.

**Comment by usmanazizgroupdocs** [comment]
@egorovpavel Thanks for providing the details.

**Comment by egorovpavel** [comment]
@usmanazizgroupdocs we improved UI for displaying spreadsheets. Please update to the latest version.
