### ISSUE TITLE
Custom viewer URL

### ISSUE THREAD

**Issue by erjezus** [groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring#53]
Good morning, these changes are not compatible with the new version of the viewer. Has this functionality been implemented permanently?

https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring/pull/41/files

**Comment by bobkovalex** [comment]
Hi @erjezus 

No, this Pull Request were used as an example on how to modify UI/UX of our front-end examples.
However this example is outdated, so we are currently prepering new example, which we will share ASAP.

@atirtahirgroupdocs FYI

Thanks.
