### ISSUE TITLE
Legacy classes and methods

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring#54]
This issue is raised in https://forum.groupdocs.com/t/java-spring-viewer-legacy-code/8186.

Hi,
In current version of the UI, most of the classes and methods are deprecated (e.g. DocumentInfoContainer) and they are removed in latest version. Can you please share a plan to upgrade the UI as per new API version?
Thanks

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

Approximate ETA is next few weeks.

Regards

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

Project has been updated to latest GroupDocs.Viewer for Java API

Regards
