### ISSUE TITLE
An SWG file is always downloaded every time I open a Visio (VSDX) file

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-viewer/GroupDocs.Viewer-for-Java-Spring#58]
This issue is raised in https://forum.groupdocs.com/t/java-spring-20-7-update/8824
This issue could be reproduced using any sample VSDX file. When you try to open the Visio file, an SVG file is automatically downloaded and VSDX is not rendered properly. 
Have a look at the attached screenshot. 
![issue](https://user-images.githubusercontent.com/15940608/93522226-93c0be80-f94a-11ea-931b-ca112ab70a3d.PNG)
This happens in latest version. However, in 1.14.32 it was working fine.

**Comment by bobkovalex** [comment]
Hi @atirtahirgroupdocs 

Thank you for the report, we will look into this.

**Comment by bobkovalex** [comment]
@atirtahirgroupdocs 

Reported issue has been verified and fixed.
Please checkout latest commit from master branch.

Regards
